
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v4

    # the OBS build actually uses the image from YaST:Head, patch the config
    # to use the same base image also in the GitHub Action
    - name: Patch the Dockerfile
      run: sed -i 's@^FROM\\b.*$@FROM registry.opensuse.org/yast/head/images/opensuse/tumbleweed:latest@' package/Dockerfile

    - name: Build the Docker Image
      run: docker build -t yast-rake package

    # check that the YaST rake tasks can be loaded
    - name: Smoke Test
      run: docker run --rm yast-rake rake -r yast/rake -V
